deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app # Make sure this name matches your build job's artifact name

      # ▼▼▼ ADD THIS LOGIN STEP ▼▼▼
      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BA177B937CB744819220295DD7EC7503 }} # Use the same secret
      # ▲▲▲ LOGIN STEP ENDS HERE ▲▲▲

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-002-gen10-step3-1-py-oshima42'
          slot-name: 'Production'
          package: .
